<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence+, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter+)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif+)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site+)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref+)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites+)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value+)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array+)>

]>
<!-- Begin document body -->
<MEME version="4.8.1" release="Tue Feb  7 14:03:40 EST 2012">
<training_set datafile="Okt1_Genes.fa" length="384">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="chrX:36040063-36040663:-1,ENSG00000206733,U6" length="601" weight="1.000000" />
<sequence id="sequence_1" name="chrX:37728861-37729461:1,ENSG00000206983,U6" length="601" weight="1.000000" />
<sequence id="sequence_2" name="chrX:41778503-41779103:-1,ENSG00000251807,U6" length="601" weight="1.000000" />
<sequence id="sequence_3" name="chrX:41998684-41999284:-1,ENSG00000212560,U6" length="601" weight="1.000000" />
<sequence id="sequence_4" name="chrX:42033539-42034139:-1,ENSG00000206896,U6" length="601" weight="1.000000" />
<sequence id="sequence_5" name="chrX:46946404-46947004:1,ENSG00000206685,U6" length="601" weight="1.000000" />
<sequence id="sequence_6" name="chrX:47211249-47211849:-1,ENSG00000201450,U6" length="601" weight="1.000000" />
<sequence id="sequence_7" name="chrX:48582867-48583467:-1,ENSG00000206723,U6" length="601" weight="1.000000" />
<sequence id="sequence_8" name="chrX:48635387-48635987:-1,ENSG00000207367,U6" length="601" weight="1.000000" />
<sequence id="sequence_9" name="chrX:54369478-54370078:1,ENSG00000207104,U6" length="601" weight="1.000000" />
<sequence id="sequence_10" name="chrX:71185825-71186425:-1,ENSG00000201392,U6" length="601" weight="1.000000" />
<sequence id="sequence_11" name="chrX:73899387-73899987:1,ENSG00000199885,U6" length="601" weight="1.000000" />
<sequence id="sequence_12" name="chrX:74422037-74422637:1,ENSG00000199601,U6" length="601" weight="1.000000" />
<sequence id="sequence_13" name="chrX:75464866-75465466:1,ENSG00000201826,U6" length="601" weight="1.000000" />
<sequence id="sequence_14" name="chrX:77092285-77092885:1,ENSG00000200906,U6" length="601" weight="1.000000" />
<sequence id="sequence_15" name="chrX:81256677-81257277:-1,ENSG00000206826,U6" length="601" weight="1.000000" />
<sequence id="sequence_16" name="chrX:89852240-89852840:-1,ENSG00000207515,U6" length="601" weight="1.000000" />
<sequence id="sequence_17" name="chrX:101933642-101934242:-1,ENSG00000252294,U6" length="601" weight="1.000000" />
<sequence id="sequence_18" name="chrX:108069493-108070093:1,ENSG00000201443,U6" length="601" weight="1.000000" />
<sequence id="sequence_19" name="chrX:115984814-115985414:-1,ENSG00000206752,U6" length="601" weight="1.000000" />
<sequence id="sequence_20" name="chrX:132665755-132666355:-1,ENSG00000206765,U6" length="601" weight="1.000000" />
<sequence id="sequence_21" name="chrX:146908296-146908896:1,ENSG00000202051,U6" length="601" weight="1.000000" />
<sequence id="sequence_22" name="chrY:4043032-4043632:-1,ENSG00000252900,U6" length="601" weight="1.000000" />
<sequence id="sequence_23" name="chrY:18360314-18360914:1,ENSG00000252173,U6" length="601" weight="1.000000" />
<sequence id="sequence_24" name="chrY:18448170-18448770:-1,ENSG00000252323,U6" length="601" weight="1.000000" />
<sequence id="sequence_25" name="chrY:21180874-21181474:-1,ENSG00000252766,U6" length="601" weight="1.000000" />
<sequence id="sequence_26" name="chr1:157788-158388:-1,ENSG00000222623,U6" length="601" weight="1.000000" />
<sequence id="sequence_27" name="chr1:693617-694217:-1,ENSG00000223181,U6" length="601" weight="1.000000" />
<sequence id="sequence_28" name="chr1:8943493-8944093:-1,ENSG00000201725,U6" length="601" weight="1.000000" />
<sequence id="sequence_29" name="chr1:10222825-10223425:1,ENSG00000201746,U6" length="601" weight="1.000000" />
<sequence id="sequence_30" name="chr1:26290187-26290787:1,ENSG00000207237,U6" length="601" weight="1.000000" />
<sequence id="sequence_31" name="chr1:38350194-38350794:1,ENSG00000222282,U6" length="601" weight="1.000000" />
<sequence id="sequence_32" name="chr1:38861830-38862430:1,ENSG00000200796,U6" length="601" weight="1.000000" />
<sequence id="sequence_33" name="chr1:51847479-51848079:1,ENSG00000206595,U6" length="601" weight="1.000000" />
<sequence id="sequence_34" name="chr1:55863686-55864286:1,ENSG00000252162,U6" length="601" weight="1.000000" />
<sequence id="sequence_35" name="chr1:67661322-67661922:1,ENSG00000253074,U6" length="601" weight="1.000000" />
<sequence id="sequence_36" name="chr1:68006309-68006909:1,ENSG00000207504,U6" length="601" weight="1.000000" />
<sequence id="sequence_37" name="chr1:77218319-77218919:1,ENSG00000199921,U6" length="601" weight="1.000000" />
<sequence id="sequence_38" name="chr1:102194194-102194794:-1,ENSG00000252530,U6" length="601" weight="1.000000" />
<sequence id="sequence_39" name="chr1:112032946-112033546:-1,ENSG00000200360,U6" length="601" weight="1.000000" />
<sequence id="sequence_40" name="chr1:150673841-150674441:1,ENSG00000206931,U6" length="601" weight="1.000000" />
<sequence id="sequence_41" name="chr1:151720077-151720677:-1,ENSG00000206980,U6" length="601" weight="1.000000" />
<sequence id="sequence_42" name="chr1:153303597-153304197:1,ENSG00000207321,U6" length="601" weight="1.000000" />
<sequence id="sequence_43" name="chr1:154267478-154268078:1,ENSG00000212292,U6" length="601" weight="1.000000" />
<sequence id="sequence_44" name="chr1:154269625-154270225:1,ENSG00000222457,U6" length="601" weight="1.000000" />
<sequence id="sequence_45" name="chr1:168232620-168233220:-1,ENSG00000206880,U6" length="601" weight="1.000000" />
<sequence id="sequence_46" name="chr1:171387790-171388390:-1,ENSG00000202082,U6" length="601" weight="1.000000" />
<sequence id="sequence_47" name="chr1:172335179-172335779:1,ENSG00000206684,U6" length="601" weight="1.000000" />
<sequence id="sequence_48" name="chr1:182951354-182951954:-1,ENSG00000207472,U6" length="601" weight="1.000000" />
<sequence id="sequence_49" name="chr1:205563668-205564268:1,ENSG00000206762,U6" length="601" weight="1.000000" />
<sequence id="sequence_50" name="chr1:212865105-212865705:1,ENSG00000207491,U6" length="601" weight="1.000000" />
<sequence id="sequence_51" name="chr1:222010680-222011280:-1,ENSG00000200033,U6" length="601" weight="1.000000" />
<sequence id="sequence_52" name="chr1:222676978-222677578:-1,ENSG00000222399,U6" length="601" weight="1.000000" />
<sequence id="sequence_53" name="chr1:224163852-224164452:-1,ENSG00000212157,U6" length="601" weight="1.000000" />
<sequence id="sequence_54" name="chr1:242187257-242187857:-1,ENSG00000223119,U6" length="601" weight="1.000000" />
<sequence id="sequence_55" name="chr1:243244462-243245062:-1,ENSG00000212230,U6" length="601" weight="1.000000" />
<sequence id="sequence_56" name="chr1:245185816-245186416:1,ENSG00000252282,U6" length="601" weight="1.000000" />
<sequence id="sequence_57" name="chr1:246352321-246352921:-1,ENSG00000202184,U6" length="601" weight="1.000000" />
<sequence id="sequence_58" name="chr1:249206895-249207495:-1,ENSG00000200495,U6" length="601" weight="1.000000" />
<sequence id="sequence_59" name="chr2:4992366-4992966:1,ENSG00000207192,U6" length="601" weight="1.000000" />
<sequence id="sequence_60" name="chr2:11373613-11374213:1,ENSG00000207267,U6" length="601" weight="1.000000" />
<sequence id="sequence_61" name="chr2:20375065-20375665:1,ENSG00000200763,U6" length="601" weight="1.000000" />
<sequence id="sequence_62" name="chr2:32439532-32440132:-1,ENSG00000201113,U6" length="601" weight="1.000000" />
<sequence id="sequence_63" name="chr2:35696170-35696770:1,ENSG00000207255,U6" length="601" weight="1.000000" />
<sequence id="sequence_64" name="chr2:37558920-37559520:-1,ENSG00000207364,U6" length="601" weight="1.000000" />
<sequence id="sequence_65" name="chr2:43318533-43319133:-1,ENSG00000207087,U6" length="601" weight="1.000000" />
<sequence id="sequence_66" name="chr2:44381935-44382535:-1,ENSG00000252599,U6" length="601" weight="1.000000" />
<sequence id="sequence_67" name="chr2:48008017-48008617:1,ENSG00000251872,U6" length="601" weight="1.000000" />
<sequence id="sequence_68" name="chr2:49460939-49461539:-1,ENSG00000206915,U6" length="601" weight="1.000000" />
<sequence id="sequence_69" name="chr2:61832250-61832850:1,ENSG00000206973,U6" length="601" weight="1.000000" />
<sequence id="sequence_70" name="chr2:69409508-69410108:1,ENSG00000199460,U6" length="601" weight="1.000000" />
<sequence id="sequence_71" name="chr2:79109253-79109853:1,ENSG00000200048,U6" length="601" weight="1.000000" />
<sequence id="sequence_72" name="chr2:82495235-82495835:1,ENSG00000252897,U6" length="601" weight="1.000000" />
<sequence id="sequence_73" name="chr2:88683017-88683617:-1,ENSG00000212133,U6" length="601" weight="1.000000" />
<sequence id="sequence_74" name="chr2:113843881-113844481:1,ENSG00000201805,U6" length="601" weight="1.000000" />
<sequence id="sequence_75" name="chr2:125746295-125746895:1,ENSG00000206726,U6" length="601" weight="1.000000" />
<sequence id="sequence_76" name="chr2:128602309-128602909:1,ENSG00000202532,U6" length="601" weight="1.000000" />
<sequence id="sequence_77" name="chr2:133164332-133164932:-1,ENSG00000252705,U6" length="601" weight="1.000000" />
<sequence id="sequence_78" name="chr2:150467189-150467789:-1,ENSG00000207270,U6" length="601" weight="1.000000" />
<sequence id="sequence_79" name="chr2:158768783-158769383:1,ENSG00000251980,U6" length="601" weight="1.000000" />
<sequence id="sequence_80" name="chr2:175886441-175887041:1,ENSG00000212167,U6" length="601" weight="1.000000" />
<sequence id="sequence_81" name="chr2:183738068-183738668:1,ENSG00000207178,U6" length="601" weight="1.000000" />
<sequence id="sequence_82" name="chr2:188135432-188136032:-1,ENSG00000199626,U6" length="601" weight="1.000000" />
<sequence id="sequence_83" name="chr2:196535099-196535699:-1,ENSG00000201813,U6" length="601" weight="1.000000" />
<sequence id="sequence_84" name="chr2:198311968-198312568:1,ENSG00000206836,U6" length="601" weight="1.000000" />
<sequence id="sequence_85" name="chr2:202791661-202792261:1,ENSG00000212184,U6" length="601" weight="1.000000" />
<sequence id="sequence_86" name="chr2:208545264-208545864:-1,ENSG00000199251,U6" length="601" weight="1.000000" />
<sequence id="sequence_87" name="chr2:208884366-208884966:-1,ENSG00000212246,U6" length="601" weight="1.000000" />
<sequence id="sequence_88" name="chr3:324376-324976:-1,ENSG00000252017,U6" length="601" weight="1.000000" />
<sequence id="sequence_89" name="chr3:9960738-9961338:-1,ENSG00000212327,U6" length="601" weight="1.000000" />
<sequence id="sequence_90" name="chr3:15380755-15381355:1,ENSG00000201162,U6" length="601" weight="1.000000" />
<sequence id="sequence_91" name="chr3:20549149-20549749:-1,ENSG00000206807,U6" length="601" weight="1.000000" />
<sequence id="sequence_92" name="chr3:23682984-23683584:-1,ENSG00000212269,U6" length="601" weight="1.000000" />
<sequence id="sequence_93" name="chr3:27307075-27307675:-1,ENSG00000207251,U6" length="601" weight="1.000000" />
<sequence id="sequence_94" name="chr3:52585860-52586460:-1,ENSG00000252768,U6" length="601" weight="1.000000" />
<sequence id="sequence_95" name="chr3:66343545-66344145:-1,ENSG00000206759,U6" length="601" weight="1.000000" />
<sequence id="sequence_96" name="chr3:77860896-77861496:-1,ENSG00000206891,U6" length="601" weight="1.000000" />
<sequence id="sequence_97" name="chr3:86283970-86284570:1,ENSG00000251773,U6" length="601" weight="1.000000" />
<sequence id="sequence_98" name="chr3:93695372-93695972:1,ENSG00000200366,U6" length="601" weight="1.000000" />
<sequence id="sequence_99" name="chr3:96327662-96328262:-1,ENSG00000199286,U6" length="601" weight="1.000000" />
<sequence id="sequence_100" name="chr3:101334169-101334769:1,ENSG00000252348,U6" length="601" weight="1.000000" />
<sequence id="sequence_101" name="chr3:106725914-106726514:1,ENSG00000252626,U6" length="601" weight="1.000000" />
<sequence id="sequence_102" name="chr3:124837945-124838545:-1,ENSG00000199327,U6" length="601" weight="1.000000" />
<sequence id="sequence_103" name="chr3:126959818-126960418:-1,ENSG00000201288,U6" length="601" weight="1.000000" />
<sequence id="sequence_104" name="chr3:133383278-133383878:1,ENSG00000252641,U6" length="601" weight="1.000000" />
<sequence id="sequence_105" name="chr3:134499370-134499970:-1,ENSG00000253087,U6" length="601" weight="1.000000" />
<sequence id="sequence_106" name="chr3:136148926-136149526:-1,ENSG00000200571,U6" length="601" weight="1.000000" />
<sequence id="sequence_107" name="chr3:141621773-141622373:-1,ENSG00000200389,U6" length="601" weight="1.000000" />
<sequence id="sequence_108" name="chr3:169437982-169438582:-1,ENSG00000206777,U6" length="601" weight="1.000000" />
<sequence id="sequence_109" name="chr3:171222041-171222641:-1,ENSG00000207114,U6" length="601" weight="1.000000" />
<sequence id="sequence_110" name="chr3:175115038-175115638:-1,ENSG00000199792,U6" length="601" weight="1.000000" />
<sequence id="sequence_111" name="chr3:180298344-180298944:1,ENSG00000199986,U6" length="601" weight="1.000000" />
<sequence id="sequence_112" name="chr3:186489637-186490237:-1,ENSG00000207505,U6" length="601" weight="1.000000" />
<sequence id="sequence_113" name="chr3:194254213-194254813:-1,ENSG00000252053,U6" length="601" weight="1.000000" />
<sequence id="sequence_114" name="chr3:194935015-194935615:1,ENSG00000206600,U6" length="601" weight="1.000000" />
<sequence id="sequence_115" name="chr3:197720971-197721571:1,ENSG00000201622,U6" length="601" weight="1.000000" />
<sequence id="sequence_116" name="chr3:197923116-197923716:1,ENSG00000222792,U6" length="601" weight="1.000000" />
<sequence id="sequence_117" name="chr4:16010311-16010911:-1,ENSG00000251758,U6" length="601" weight="1.000000" />
<sequence id="sequence_118" name="chr4:22120105-22120705:1,ENSG00000239001,U6" length="601" weight="1.000000" />
<sequence id="sequence_119" name="chr4:41086123-41086723:1,ENSG00000199790,U6" length="601" weight="1.000000" />
<sequence id="sequence_120" name="chr4:53360514-53361114:1,ENSG00000199924,U6" length="601" weight="1.000000" />
<sequence id="sequence_121" name="chr4:54131635-54132235:-1,ENSG00000207385,U6" length="601" weight="1.000000" />
<sequence id="sequence_122" name="chr4:71713836-71714436:-1,ENSG00000252880,U6" length="601" weight="1.000000" />
<sequence id="sequence_123" name="chr4:71717346-71717946:1,ENSG00000207007,U6" length="601" weight="1.000000" />
<sequence id="sequence_124" name="chr4:83924064-83924664:1,ENSG00000251874,U6" length="601" weight="1.000000" />
<sequence id="sequence_125" name="chr4:85807540-85808140:-1,ENSG00000252062,U6" length="601" weight="1.000000" />
<sequence id="sequence_126" name="chr4:97073455-97074055:-1,ENSG00000201744,U6" length="601" weight="1.000000" />
<sequence id="sequence_127" name="chr4:102644532-102645132:1,ENSG00000199529,U6" length="601" weight="1.000000" />
<sequence id="sequence_128" name="chr4:106327653-106328253:1,ENSG00000200917,U6" length="601" weight="1.000000" />
<sequence id="sequence_129" name="chr4:110912980-110913580:1,ENSG00000207260,U6" length="601" weight="1.000000" />
<sequence id="sequence_130" name="chr4:112252067-112252667:1,ENSG00000200963,U6" length="601" weight="1.000000" />
<sequence id="sequence_131" name="chr4:119527104-119527704:1,ENSG00000223225,U6" length="601" weight="1.000000" />
<sequence id="sequence_132" name="chr4:120355164-120355764:-1,ENSG00000223208,U6" length="601" weight="1.000000" />
<sequence id="sequence_133" name="chr4:122113959-122114559:-1,ENSG00000252183,U6" length="601" weight="1.000000" />
<sequence id="sequence_134" name="chr4:136236578-136237178:-1,ENSG00000207188,U6" length="601" weight="1.000000" />
<sequence id="sequence_135" name="chr4:140152174-140152774:-1,ENSG00000252362,U6" length="601" weight="1.000000" />
<sequence id="sequence_136" name="chr4:140177815-140178415:-1,ENSG00000206722,U6" length="601" weight="1.000000" />
<sequence id="sequence_137" name="chr4:152221169-152221769:1,ENSG00000252544,U6" length="601" weight="1.000000" />
<sequence id="sequence_138" name="chr4:154186808-154187408:-1,ENSG00000252030,U6" length="601" weight="1.000000" />
<sequence id="sequence_139" name="chr4:165707941-165708541:1,ENSG00000201050,U6" length="601" weight="1.000000" />
<sequence id="sequence_140" name="chr4:169607768-169608368:-1,ENSG00000206613,U6" length="601" weight="1.000000" />
<sequence id="sequence_141" name="chr4:174367756-174368356:-1,ENSG00000252898,U6" length="601" weight="1.000000" />
<sequence id="sequence_142" name="chr4:184596769-184597369:-1,ENSG00000201433,U6" length="601" weight="1.000000" />
<sequence id="sequence_143" name="chr5:25701334-25701934:-1,ENSG00000201016,U6" length="601" weight="1.000000" />
<sequence id="sequence_144" name="chr5:31595677-31596277:-1,ENSG00000199765,U6" length="601" weight="1.000000" />
<sequence id="sequence_145" name="chr5:32309267-32309867:1,ENSG00000207052,U6" length="601" weight="1.000000" />
<sequence id="sequence_146" name="chr5:33888168-33888768:-1,ENSG00000201623,U6" length="601" weight="1.000000" />
<sequence id="sequence_147" name="chr5:37620091-37620691:-1,ENSG00000222743,U6" length="601" weight="1.000000" />
<sequence id="sequence_148" name="chr5:37700440-37701040:-1,ENSG00000206743,U6" length="601" weight="1.000000" />
<sequence id="sequence_149" name="chr5:53207854-53208454:-1,ENSG00000222960,U6" length="601" weight="1.000000" />
<sequence id="sequence_150" name="chr5:60959967-60960567:-1,ENSG00000212215,U6" length="601" weight="1.000000" />
<sequence id="sequence_151" name="chr5:63868895-63869495:1,ENSG00000201869,U6" length="601" weight="1.000000" />
<sequence id="sequence_152" name="chr5:74020930-74021530:-1,ENSG00000207336,U6" length="601" weight="1.000000" />
<sequence id="sequence_153" name="chr5:75005325-75005925:-1,ENSG00000207333,U6" length="601" weight="1.000000" />
<sequence id="sequence_154" name="chr5:76244115-76244715:1,ENSG00000252684,U6" length="601" weight="1.000000" />
<sequence id="sequence_155" name="chr5:79661552-79662152:-1,ENSG00000206774,U6" length="601" weight="1.000000" />
<sequence id="sequence_156" name="chr5:86595515-86596115:-1,ENSG00000207452,U6" length="601" weight="1.000000" />
<sequence id="sequence_157" name="chr5:86716165-86716765:-1,ENSG00000200462,U6" length="601" weight="1.000000" />
<sequence id="sequence_158" name="chr5:98224934-98225534:1,ENSG00000222610,U6" length="601" weight="1.000000" />
<sequence id="sequence_159" name="chr5:104115991-104116591:-1,ENSG00000252881,U6" length="601" weight="1.000000" />
<sequence id="sequence_160" name="chr5:118474053-118474653:1,ENSG00000206786,U6" length="601" weight="1.000000" />
<sequence id="sequence_161" name="chr5:125888995-125889595:-1,ENSG00000200347,U6" length="601" weight="1.000000" />
<sequence id="sequence_162" name="chr5:126091010-126091610:-1,ENSG00000252185,U6" length="601" weight="1.000000" />
<sequence id="sequence_163" name="chr5:137405048-137405648:-1,ENSG00000222924,U6" length="601" weight="1.000000" />
<sequence id="sequence_164" name="chr5:139097576-139098176:-1,ENSG00000200756,U6" length="601" weight="1.000000" />
<sequence id="sequence_165" name="chr5:148437120-148437720:-1,ENSG00000251842,U6" length="601" weight="1.000000" />
<sequence id="sequence_166" name="chr5:148986205-148986805:-1,ENSG00000222213,U6" length="601" weight="1.000000" />
<sequence id="sequence_167" name="chr5:161904396-161904996:1,ENSG00000201474,U6" length="601" weight="1.000000" />
<sequence id="sequence_168" name="chr5:168978952-168979552:1,ENSG00000206614,U6" length="601" weight="1.000000" />
<sequence id="sequence_169" name="chr5:175130400-175131000:1,ENSG00000200648,U6" length="601" weight="1.000000" />
<sequence id="sequence_170" name="chr5:180433780-180434380:1,ENSG00000206686,U6" length="601" weight="1.000000" />
<sequence id="sequence_171" name="chr5:180728467-180729067:1,ENSG00000222533,U6" length="601" weight="1.000000" />
<sequence id="sequence_172" name="chr6:14646265-14646865:1,ENSG00000206960,U6" length="601" weight="1.000000" />
<sequence id="sequence_173" name="chr6:15324604-15325204:-1,ENSG00000201519,U6" length="601" weight="1.000000" />
<sequence id="sequence_174" name="chr6:19642661-19643261:-1,ENSG00000200957,U6" length="601" weight="1.000000" />
<sequence id="sequence_175" name="chr6:20452605-20453205:-1,ENSG00000222431,U6" length="601" weight="1.000000" />
<sequence id="sequence_176" name="chr6:24365378-24365978:1,ENSG00000202050,U6" length="601" weight="1.000000" />
<sequence id="sequence_177" name="chr6:25383326-25383926:1,ENSG00000207490,U6" length="601" weight="1.000000" />
<sequence id="sequence_178" name="chr6:27563690-27564290:1,ENSG00000206671,U6" length="601" weight="1.000000" />
<sequence id="sequence_179" name="chr6:31337410-31338010:1,ENSG00000201658,U6" length="601" weight="1.000000" />
<sequence id="sequence_180" name="chr6:41270211-41270811:-1,ENSG00000206745,U6" length="601" weight="1.000000" />
<sequence id="sequence_181" name="chr6:41986153-41986753:-1,ENSG00000206875,U6" length="601" weight="1.000000" />
<sequence id="sequence_182" name="chr6:45985981-45986581:1,ENSG00000212468,U6" length="601" weight="1.000000" />
<sequence id="sequence_183" name="chr6:54650684-54651284:1,ENSG00000251946,U6" length="601" weight="1.000000" />
<sequence id="sequence_184" name="chr6:68256043-68256643:1,ENSG00000201015,U6" length="601" weight="1.000000" />
<sequence id="sequence_185" name="chr6:107055090-107055690:1,ENSG00000200295,U6" length="601" weight="1.000000" />
<sequence id="sequence_186" name="chr6:107186830-107187430:-1,ENSG00000202285,U6" length="601" weight="1.000000" />
<sequence id="sequence_187" name="chr6:109380718-109381318:-1,ENSG00000199944,U6" length="601" weight="1.000000" />
<sequence id="sequence_188" name="chr6:111043452-111044052:-1,ENSG00000200522,U6" length="601" weight="1.000000" />
<sequence id="sequence_189" name="chr6:111329480-111330080:-1,ENSG00000207431,U6" length="601" weight="1.000000" />
<sequence id="sequence_190" name="chr6:111412436-111413036:-1,ENSG00000200926,U6" length="601" weight="1.000000" />
<sequence id="sequence_191" name="chr6:112517649-112518249:-1,ENSG00000207044,U6" length="601" weight="1.000000" />
<sequence id="sequence_192" name="chr6:120847447-120848047:-1,ENSG00000206857,U6" length="601" weight="1.000000" />
<sequence id="sequence_193" name="chr6:139180171-139180771:-1,ENSG00000206856,U6" length="601" weight="1.000000" />
<sequence id="sequence_194" name="chr6:166131727-166132327:-1,ENSG00000206681,U6" length="601" weight="1.000000" />
<sequence id="sequence_195" name="chr7:34337111-34337711:-1,ENSG00000202431,U6" length="601" weight="1.000000" />
<sequence id="sequence_196" name="chr7:35969775-35970375:-1,ENSG00000200446,U6" length="601" weight="1.000000" />
<sequence id="sequence_197" name="chr7:39807439-39808039:1,ENSG00000252480,U6" length="601" weight="1.000000" />
<sequence id="sequence_198" name="chr7:45828683-45829283:1,ENSG00000212450,U6" length="601" weight="1.000000" />
<sequence id="sequence_199" name="chr7:45882732-45883332:1,ENSG00000202350,U6" length="601" weight="1.000000" />
<sequence id="sequence_200" name="chr7:50502577-50503177:1,ENSG00000200815,U6" length="601" weight="1.000000" />
<sequence id="sequence_201" name="chr7:55753169-55753769:1,ENSG00000252857,U6" length="601" weight="1.000000" />
<sequence id="sequence_202" name="chr7:56469767-56470367:-1,ENSG00000223330,U6" length="601" weight="1.000000" />
<sequence id="sequence_203" name="chr7:62471848-62472448:-1,ENSG00000207443,U6" length="601" weight="1.000000" />
<sequence id="sequence_204" name="chr7:65279158-65279758:1,ENSG00000200670,U6" length="601" weight="1.000000" />
<sequence id="sequence_205" name="chr7:65859677-65860277:1,ENSG00000222364,U6" length="601" weight="1.000000" />
<sequence id="sequence_206" name="chr7:66355674-66356274:1,ENSG00000212568,U6" length="601" weight="1.000000" />
<sequence id="sequence_207" name="chr7:68589756-68590356:1,ENSG00000200189,U6" length="601" weight="1.000000" />
<sequence id="sequence_208" name="chr7:72753104-72753704:-1,ENSG00000206709,U6" length="601" weight="1.000000" />
<sequence id="sequence_209" name="chr7:98392348-98392948:-1,ENSG00000207204,U6" length="601" weight="1.000000" />
<sequence id="sequence_210" name="chr7:124287272-124287872:1,ENSG00000207214,U6" length="601" weight="1.000000" />
<sequence id="sequence_211" name="chr7:139909372-139909972:-1,ENSG00000199971,U6" length="601" weight="1.000000" />